apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-ksa
  namespace: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-svc
  namespace: api
spec:
  ports:
  - name: http-api
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api:0.0.1
        name: api
        ports:
        - containerPort: 8080
          name: http-api
      serviceAccountName: api-ksa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: api-svc
            port:
              number: 80
        path: /
        pathType: Prefix
