---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: headlamp
spec:
  hosts:
  - "headlamp.playground.local"
  gateways:
  - playground-local-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: headlamp.kube-system.svc.cluster.local
        port:
          number: 80
