version: '3.7'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: playground
    ports:
      - 27017:27017
    volumes:
      - ./src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - 3306:3306
  postgresdb:
    image: postgres:14.4
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
  api:
    build: src/api/
    container_name: api
    restart: always
    environment:
      # most defaulted, see src/api/config.go
      # mysql
      MYSQL_ENABLED: true
      MYSQL_HOST: mysqldb
      # postgres
      POSTGRES_ENABLED: true
      POSTGRES_HOST: postgresdb
      # mongo
      MONGO_ENABLED: true
      MONGO_HOST: mongodb
    ports:
      - 8080:8080
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/api/v1/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - mongodb
      - mysqldb
      - postgresdb
    links:
      - mongodb
      - mysqldb
      - postgresdb
