[settings]
lockfile = true

[tools]
task = "latest"

kind = "latest"
colima = "latest"
rancher = "latest"

# kubectl = "latest"
# helm = "latest"
# flux2 = "latest"
# terraform-docs = "latest"


opentofu = "latest"
prek = "latest"
tilt = "latest"
