---
version: '3'


vars:
  TEXT_BOLD: { sh: tput bold }
  TEXT_GRAY: { sh: tput setaf 0 }
  TEXT_RED: { sh: tput setaf 1 }
  TEXT_GREEN: { sh: tput setaf 2 }
  TEXT_YELLOW: { sh: tput setaf 3 }
  TEXT_DARK_BLUE: { sh: tput setaf 4 }
  TEXT_PURPLE: { sh: tput setaf 5 }
  TEXT_LIGHT_BLUE: { sh: tput setaf 6 }
  TEXT_RESET: { sh: tput sgr0 }

  CLUSTERS_FOLDER: kind
  CLUSTERS:
    sh: find ./{{.CLUSTERS_FOLDER}} -maxdepth 1 -type f

  DEPENDENCIES: [docker, kubectl, kind, flux]

  API_TAG: 0.0.7

tasks:
  default:
    aliases: [all]
    silent: true
    deps:
      - app

  clean:
    aliases: [delete]
    ignore_error: true
    silent: true
    cmds:
      - task: kind:clean
      - task: rancher:clean

  check-dependencies:
    silent: true
    cmds:
      - |
        {{range .DEPENDENCIES}}
          if ! which {{.}} > /dev/null; then
            echo {{.}} not found;
            exit 1;
          fi
        {{end}}

  # HELPER START
  wait-for-crd:
    internal: true
    silent: true
    cmds:
      - |
        attempts=30
        while ! kubectl wait --for condition=established --timeout=60s crd {{.CRD}} > /dev/null 2>&1
        do
          echo "{{.TEXT_YELLOW}}Waiting for CRD to be ready....{{.TEXT_RESET}}"
          sleep 5
          let attempts=$attempts-1
          if [ $attempts -eq 0 ]
          then
            echo "{{.TEXT_RED}}CRD never got ready!{{.TEXT_RESET}}"
            exit 1
          fi
        done
        echo "{{.TEXT_GREEN}}CRD came up!{{.TEXT_RESET}}"
  # HELPER END

  # TEXT START
  text:test:
    silent: true
    cmds:
      - echo "TEXT_NORMAL"
      - echo "{{.TEXT_BOLD}}TEXT_BOLD{{.TEXT_RESET}}"
      - echo "{{.TEXT_GRAY}}TEXT_GRAY{{.TEXT_RESET}}"
      - echo "{{.TEXT_RED}}TEXT_RED{{.TEXT_RESET}}"
      - echo "{{.TEXT_GREEN}}TEXT_GREEN{{.TEXT_RESET}}"
      - echo "{{.TEXT_YELLOW}}TEXT_YELLOW{{.TEXT_RESET}}"
      - echo "{{.TEXT_DARK_BLUE}}TEXT_DARK_BLUE{{.TEXT_RESET}}"
      - echo "{{.TEXT_PURPLE}}TEXT_PURPLE{{.TEXT_RESET}}"
      - echo "{{.TEXT_LIGHT_BLUE}}TEXT_LIGHT_BLUE{{.TEXT_RESET}}"
  # TEXT END

  # RANCHER START
  rancher:
    deps:
      - rancher:run

  rancher:run:
    run: once
    silent: true
    cmds:
      - rdctl start --application.start-in-background
      - |
        attempts=30
        while ! docker info > /dev/null 2>&1
        do
          echo "{{.TEXT_YELLOW}}Waiting for docker to come up....{{.TEXT_RESET}}"
          sleep 5
          let attempts=$attempts-1
          if [ $attempts -eq 0 ]
          then
            echo "{{.TEXT_RED}}docker never came up!{{.TEXT_RESET}}"
            exit 1
          fi
        done
        echo "{{.TEXT_GREEN}}Docker came up!{{.TEXT_RESET}}"
    status:
      - rdctl list-settings > /dev/null 2>&1
      - docker info > /dev/null 2>&1

  rancher:clean:
    # prompt: Do you want to update quit Rancher Desktop?
    run: once
    cmds:
      - rdctl shutdown
  # RANCHER END

  # KIND START
  kind:
    silent: true
    aliases: ["cluster"]
    run: once
    cmds:
      - task: kind:cloud-provider:run

  kind:print:
    silent: true
    cmds:
      - |
        {{range .CLUSTERS | splitArgs}}
          # echo "{{.}}"
          cat "{{.}}" | yq .name
        {{end}}

  kind:create:
    run: once
    silent: true
    deps:
      - rancher:run
    cmds:
      - |
        {{range .CLUSTERS | splitArgs}}
          cluster_name=$(yq '.name' {{.}})
          if ! kubectl cluster-info --context kind-${cluster_name} > /dev/null 2>&1
          then
            kind create cluster --config={{.}}
          else
            echo "$cluster_name already created"
          fi
        {{end}}
    status:
      - |
        {{range .CLUSTERS | splitArgs}}
          cluster_name=$(yq '.name' {{.}})
          kubectl cluster-info --context kind-${cluster_name}
        {{end}}

  kind:clean:
    silent: true
    deps:
      - kind:cloud-provider:clean
    cmds:
      - |
        if docker info > /dev/null 2>&1; then
          kind delete clusters --all
        else
          echo "{{.TEXT_GRAY}}docker is not running so no clusters to clean right now{{.TEXT_RESET}}"
        fi

  kind:cloud-provider:run:
    run: once
    silent: true
    deps:
      - kind:create
    interactive: true
    cmds:
      - echo "{{.TEXT_YELLOW}}sudo needed for cloud-provider-kind{{.TEXT_RESET}}"
      - sudo -v
      - bash -c 'nohup sudo cloud-provider-kind --gateway-channel standard >/dev/null 2>&1 &'
      - echo "{{.TEXT_GREEN}}$(pgrep sudo cloud-provider-kind){{.TEXT_RESET}}"
      - task: wait-for-crd
        vars: { CRD: "httproutes.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "gateways.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "gatewayclasses.gateway.networking.k8s.io" }
    status:
      - pgrep sudo cloud-provider-kind

  kind:cloud-provider:clean:
    silent: true
    interactive: true
    cmds:
      - |
        if pgrep sudo cloud-provider-kind > /dev/null 2>&1; then
          echo "{{.TEXT_YELLOW}}sudo needed for cloud-provider-kind{{.TEXT_RESET}}"
          sudo -v
          sudo pkill cloud-provider-kind
          echo "{{.TEXT_GREEN}}killed{{.TEXT_RESET}}"
        else
          echo "{{.TEXT_GRAY}}cloud-provider-kind is not running{{.TEXT_RESET}}"
        fi

  kind:cloud-provider:restart:
    interactive: true
    cmds:
      - task: kind:cloud-provider:clean
      - task: kind:cloud-provider:run
  # KIND END

  # INFRA START
  infra:
    aliases: [infrastructure]
    cmds:
      - task: infra:metrics-server:install
      - task: infra:istio
      - task: infra:kube-prom-stack:install
      - task: infra:argo-rollouts:install

  ## FLUX START
  infra:flux:install:
    run: once
    deps:
      - kind
    cmds:
      - flux install --components=source-controller,helm-controller
    status:
      - |
        namespace_check=$(kubectl get ns flux-system -oyaml | yq .status.phase)
        if [[ "$namespace_check" == "Active" ]]; then
          exit 0
        else
          exit -1
        fi

  infra:flux:clean:
    aliases: [infra:flux:uninstall, infra:flux:delete]
    interactive: true
    cmds:
      - flux uninstall
  ## FLUX END

  ## SOURCES START
  infra:sources:install:
    run: once
    deps:
      - infra:flux:install
    cmds:
      # - task: wait-for-crd
      #   vars: { CRD: "gateways.gateway.networking.k8s.io" }
      - kubectl apply -k deploy/infrastructure/sources
    status:
      - kubectl diff -k deploy/infrastructure/sources
   ## SOURCES END

  ## METRICS_SERVER START
  infra:metrics-server:install:
    deps:
      - infra:flux:install
      - infra:sources:install
    cmds:
      - kubectl apply -k deploy/infrastructure/metrics-server
    status:
      - kubectl diff -k deploy/infrastructure/metrics-server

  infra:metrics-server:clean:
    cmds:
      - kubectl delete -k deploy/infrastructure/metrics-server
  ## METRICS_SERVER END

  ## ISTIO START
  infra:istio:
    run: once
    deps:
      - infra:sources:install
    cmds:
      - task: infra:istio:base:install
      - task: infra:istio:gateway:install
      # - task: infra:istio:update-etc-hosts

  infra:istio:base:install:
    run: once
    deps:
      - infra:flux:install
      - infra:sources:install
    cmds:
      - kubectl apply -k deploy/infrastructure/istio/base
    status:
      - kubectl diff -k deploy/infrastructure/istio/base

  infra:istio:gateway:install:
    run: once
    deps:
      - infra:flux:install
      - infra:sources:install
      - infra:istio:base:install
    cmds:
      - task: wait-for-crd
        vars: { CRD: "gateways.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "gatewayclasses.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "httproutes.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "gateways.networking.istio.io" }
      - kubectl apply -k deploy/infrastructure/istio/gateway
    status:
      - kubectl diff -k deploy/infrastructure/istio/gateway

  infra:istio:update-etc-hosts:
    run: once
    prompt: Do you want to update /etc/hosts ?
    silent: true
    deps:
      - infra:istio:install
    cmds:
      - |
        if [[ -n "{{.LOAD_BALANCER_IP}}" ]]; then
          echo {{.LOAD_BALANCER_IP}}
          sudo -v
          echo "{{.LOAD_BALANCER_IP}}      playground.local" | sudo tee -a /etc/hosts
        else
          echo "{{.TEXT_RED}}Couldn't find IP address{{.TEXT_RESET}}"
        fi
    status:
      - cat /etc/hosts | grep {{.LOAD_BALANCER_IP}}
    vars:
      LOAD_BALANCER_IP:
        sh: kubectl get gateway/playground-local-gateway -n istio-gateway | awk '{print $3}' | awk NR==2  # yamllint disable-line rule:line-length
  ## ISTIO END

  ## KUBE_PROM_STACK START
  infra:kube-prom-stack:install:
    run: once
    deps:
      - infra:flux:install
      - infra:sources:install
      - infra:istio
    cmds:
      - task: wait-for-crd
        vars: { CRD: "virtualservices.networking.istio.io" }
      - kubectl apply -k deploy/infrastructure/kube-prom-stack
    status:
      - kubectl diff -k deploy/infrastructure/kube-prom-stack

  infra:kube-prom-stack:clean:
    run: once
    cmds:
      - kubectl delete -k deploy/infrastructure/kube-prom-stack
  ## KUBE_PROM_STACK END

  ## ARGO_ROLLOUTS START
  infra:argo-rollouts:install:
    run: once
    deps:
      - infra:flux:install
      - infra:sources:install
      - infra:istio
    cmds:
      - task: wait-for-crd
        vars: { CRD: "virtualservices.networking.istio.io" }
      - kubectl apply -k deploy/infrastructure/argo-rollouts
    status:
      - kubectl diff -k deploy/infrastructure/argo-rollouts

  infra:argo-rollouts:clean:
    run: once
    cmds:
      - kubectl delete -k deploy/infrastructure/argo-rollouts
  ## ARGO_ROLLOUTS END

  # INFRA END

  # APP START
  app:
    deps:
      - infra
    preconditions:
      - tilt verify-install
    cmds:
      - task: wait-for-crd
        vars: { CRD: "servicemonitors.monitoring.coreos.com" }
      - task: wait-for-crd
        vars: { CRD: "envoyfilters.networking.istio.io" }
      - task: wait-for-crd
        vars: { CRD: "virtualservices.networking.istio.io" }
      - tilt ci

  app:clean:
    cmds:
      - tilt down
  # APP END
