---
version: '3'

silent: true
run: once
failfast: true

dotenv: ['.env']

vars:
  STANDARDLOOP_TASKFILES_VERSION: "v0.0.5"
  CLUSTERS_FOLDER: kind
  CLUSTERS:
    sh: find ./{{.CLUSTERS_FOLDER}} -maxdepth 1 -type f
  API_TAG: 0.0.7
  HELM_RELEASE_TIMEOUT: "180s"
  SUPPORTED_DOCKER_ENGINES: [colima, rancher]
  SUPPORTED_K8S_ENGINES: [kind]

includes:
  color: https://raw.githubusercontent.com/standardloop/taskfiles/refs/tags/{{.STANDARDLOOP_TASKFILES_VERSION}}/color.yml
  rancher: https://raw.githubusercontent.com/standardloop/taskfiles/refs/tags/{{.STANDARDLOOP_TASKFILES_VERSION}}/rancher.yml
  colima: https://raw.githubusercontent.com/standardloop/taskfiles/refs/tags/{{.STANDARDLOOP_TASKFILES_VERSION}}/colima.yml

tasks:
  default:
    aliases: [all, playground]
    silent: true
    prompt: "This will lanuch a cluster with infrastructure and deploy an app, are you ready for this?"
    cmds:
      - task: app

  mise:
    cmds:
      - mise activate
      - mise install

  mise:clean:
    cmds:
      - mise uninstall --all
      - mise deactivate

  pre-commit: prek run --all-files

  pre-commit:update: prek update

  clean:
    aliases: [delete]
    ignore_error: true
    silent: true
    cmds:
      - task: tilt:clean
      - task: infra:clean
      - task: kind:clean
      # - task: compose:clean
      - task: docker-engine:clean

  print:
    cmds:
      - env
      - task: color:test

  # DOCKER ENGINE START
  docker-engine:test:
    requires:
      vars:
        - name: DOCKER_ENGINE
    preconditions:
      - sh: |
          {{range .SUPPORTED_DOCKER_ENGINES -}}
          if [ "{{.}}" = "{{$.DOCKER_ENGINE}}" ]; then exit 0; fi
          {{end -}}
          exit 1
        msg: |
          Invalid engine "{{.DOCKER_ENGINE}}".
          Supported engines are: {{join ", " .SUPPORTED_DOCKER_ENGINES}}
    cmds:
      - echo {{.DOCKER_ENGINE}}

  docker-engine:start:
    aliases: [docker-engine:run]
    requires:
      vars:
        - name: DOCKER_ENGINE
    preconditions:
      - sh: |
          {{range .SUPPORTED_DOCKER_ENGINES -}}
          if [ "{{.}}" = "{{$.DOCKER_ENGINE}}" ]; then exit 0; fi
          {{end -}}
          exit 1
        msg: |
          Invalid engine "{{.DOCKER_ENGINE}}".
          Supported engines are: {{join ", " .SUPPORTED_DOCKER_ENGINES}}
    cmds:
      - if: '{{eq .DOCKER_ENGINE "colima"}}'
        task: colima:start
        vars:
          FLAGS: "--network-address --cpu {{.DOCKER_ENGINE_CPUS}} --memory {{.DOCKER_ENGINE_MEMORY}}"
      - if: '{{eq .DOCKER_ENGINE "rancher"}}'
        task: rancher:start
        vars:
          FLAGS: "--virtual-machine.number-cpus {{.DOCKER_ENGINE_CPUS}} --virtual-machine.memory-in-gb {{.DOCKER_ENGINE_MEMORY}}"
    status:
      - '{{if eq .DOCKER_ENGINE "colima"}} colima status > /dev/null 2>&1 {{else}} true {{end}}'
      - '{{if eq .DOCKER_ENGINE "rancher"}} rdctl list-settings > /dev/null 2>&1 {{else}} true {{end}}'
      - docker info > /dev/null 2>&1

  docker-engine:clean:
    runs: once
    requires:
      vars:
        - name: DOCKER_ENGINE
    preconditions:
      - sh: |
          {{range .SUPPORTED_DOCKER_ENGINES -}}
          if [ "{{.}}" = "{{$.DOCKER_ENGINE}}" ]; then exit 0; fi
          {{end -}}
          exit 1
        msg: |
          Invalid engine "{{.DOCKER_ENGINE}}".
          Supported engines are: {{join ", " .SUPPORTED_DOCKER_ENGINES}}
    cmds:
      - if: '{{eq .DOCKER_ENGINE "colima"}}'
        task: colima:clean
        vars:
          FLAGS: "-f"
      - if: '{{eq .DOCKER_ENGINE "rancher"}}'
        task: rancher:clean
  # DOCKER ENGINE END

  # # COMPOSE START
  # compose:start:
  #   silent: true
  #   preconditions:
  #     - docker info > /dev/null 2>&1
  #   deps:
  #     - docker-engine:start
  #   cmds:
  #     - docker compose up -d

  # compose:clean:
  #   silent: true
  #   cmds:
  #     - |
  #       if docker info > /dev/null 2>&1; then
  #         docker compose down
  #       else
  #         echo "{{.TEXT_GRAY}}docker is not running so no compose to clean right now{{.TEXT_RESET}}"
  #       fi
  # # COMPOSE END

  # HELPER START
  wait-for-crd:
    internal: true
    silent: true
    run: always
    cmds:
      - |
        attempts=30
        while ! kubectl wait --for condition=established --timeout=60s crd {{.CRD}} > /dev/null 2>&1
        do
          echo "{{.TEXT_YELLOW}}Waiting for {{.CRD}} to be ready....{{.TEXT_RESET}}"
          sleep 5
          let attempts=$attempts-1
          if [ $attempts -eq 0 ]
          then
            echo "{{.TEXT_RED}}{{.CRD}} never got ready!{{.TEXT_RESET}}"
            exit 1
          fi
        done
        echo "{{.TEXT_GREEN}}{{.CRD}} came up!{{.TEXT_RESET}}"
    status:
      - kubectl wait --for condition=established --timeout=60s crd {{.CRD}} > /dev/null 2>&1
  # HELPER END

  # KIND START
  kind:
    silent: true
    aliases: ["cluster"]
    deps:
      - docker-engine:start
    cmds:
      - task: kind:cloud-provider:run

  kind:create:
    silent: true
    deps:
      - docker-engine:start
    cmds:
      - ./kind/local-registry-setup.sh
      - kind create cluster --config=kind/slke-1.yaml
      - ./kind/local-registry-finish.sh
    status:
      - kubectl cluster-info --context kind-slke-1

  kind:clean:
    silent: true
    deps:
      - kind:cloud-provider:clean
    cmds:
      - |
        if docker info > /dev/null 2>&1; then
          kind delete clusters --all
        else
          echo "{{.TEXT_GRAY}}docker is not running so no clusters to clean right now{{.TEXT_RESET}}"
        fi

  kind:cloud-provider:run:
    silent: true
    deps:
      - kind:create
    interactive: true
    cmds:
      - echo "{{.TEXT_YELLOW}}sudo needed for cloud-provider-kind{{.TEXT_RESET}}"
      - sudo -v
      - bash -c 'nohup sudo cloud-provider-kind --gateway-channel standard >/dev/null 2>&1 &'
      - echo "{{.TEXT_GREEN}}main pid -> $(pgrep sudo cloud-provider-kind){{.TEXT_RESET}}"
      - task: kind:cloud-provider:run:check-complete
    status:
      - pgrep sudo cloud-provider-kind

  kind:cloud-provider:run:check-complete:
    internal: true
    parallel: true
    deps:
      - task: wait-for-crd
        vars: { CRD: "httproutes.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "gateways.gateway.networking.k8s.io" }
      - task: wait-for-crd
        vars: { CRD: "gatewayclasses.gateway.networking.k8s.io" }

  kind:cloud-provider:clean:
    silent: true
    interactive: true
    cmds:
      - |
        if pgrep sudo cloud-provider-kind > /dev/null 2>&1; then
          echo "{{.TEXT_YELLOW}}sudo needed for cloud-provider-kind{{.TEXT_RESET}}"
          sudo -v
          sudo pkill cloud-provider-kind
          echo "{{.TEXT_GREEN}}killed cloud-provider-kind{{.TEXT_RESET}}"
        else
          echo "{{.TEXT_GRAY}}cloud-provider-kind is not running{{.TEXT_RESET}}"
        fi

  kind:cloud-provider:restart:
    interactive: true
    cmds:
      - task: kind:cloud-provider:clean
      - task: kind:cloud-provider:run
  # KIND END

  # INFRA START
  infra:
    aliases: [infrastructure]
    deps:
      - infra:create

  infra:create:
    deps:
      - kind:cloud-provider:run
    cmds:
      - tofu init --upgrade
      - tofu apply --auto-approve

  home: open "http://home.playground.local"

  infra:clean:
    cmds:
      - tofu destroy --auto-approve
  # INFRA END

  # APP START
  tilt:
    aliases: ["app"]
    deps:
      - infra
    preconditions:
      - tilt verify-install
    cmds:
      - task: wait-for-crd
        vars: { CRD: "servicemonitors.monitoring.coreos.com" }
      - task: wait-for-crd
        vars: { CRD: "envoyfilters.networking.istio.io" }
      - task: wait-for-crd
        vars: { CRD: "virtualservices.networking.istio.io" }
      - tilt ci

  tilt:clean:
    cmds:
      - tilt down
  # APP END
