apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: api-ns

patches:
  - path: svc-patch.yaml
    target:
      kind: Service
      version: v1
      name: api-svc

patchesStrategicMerge:
- svc-patch.yaml

images:
  - name: api
    newTag: 0.0.1
