---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http-api
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
