---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - namespace.yaml
  - service.yaml
  - ksa.yaml
  - servicemonitor.yaml
  - ingress.yaml
  - hpa.yaml
