---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
spec:
  timeout: 5m
  interval: 15m
  chart:
    spec:
      chart: gateway
      # version: latest
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  releaseName: istio-gateway
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: disabled
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system
  values:
    service:
      type: "ClusterIP"
      # ports:
      #   - name: http-envoy-prom
      #     port: 15020
      #     protocol: TCP
      #     targetPort: 15020
