---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  timeout: 5m
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      # version: latest
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  releaseName: kube-prometheus-stack
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: disabled
  values:
    commonLabels:
      prometheus: kube-prometheus-stack
      environment: playground
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      ingress:
        enabled: false
        # ingressClassName: nginx
        # # annotations:
        # hosts:
        #   - prometheus.local
        # path: /
      prometheusSpec:
        serviceMonitorSelector:
          matchLabels:
            prometheus: kube-prometheus-stack
        podMonitorSelector:
          matchLabels:
            prometheus: kube-prometheus-stack
