---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - "grafana.playground.local"
  gateways:
  - istio-gateway/playground-local-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana-service
        port:
          number: 3000
