---
alertmanager:
  enabled: false

grafana:
  ini:
    server:
      domain: grafana.local
      root_url: "http://grafana.local"
      serve_from_sub_path: true
      enforce_domain: false
      enable_gzip: true
      router_logging: true
  enabled: true
  namespaceOverride: "kube-prometheus-stack"
  defaultDashboardsEnabled: true
  adminPassword: admin
  ingress:
    enabled: true
    ingressClassName: nginx
    #annotations:
    hosts:
      - grafana.local
    path: /

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    # annotations:
    hosts:
      - prometheus.local
    path: /
  serviceMonitorSelector:
    matchLabels:
      app: api
