---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-cm
data:
  MYSQL_HOST: "mysql.mysql.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "mypassword"
  MYSQL_DBNAME: "playground"
