{
 "title": "Argo Rollouts Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "rollouts_namespace", "query": "argo-rollouts" },
   { "name": "rollouts_container_name", "query": "argo-rollouts" },
   {
    "name": "rollouts_dashboard_container_name",
    "query": "${rollouts_container_name}-dashboard"
   }
  ]
 },
 "panels": [
  { "title": "Controller Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Controller Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Controller Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Dashboard Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dashboard Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Dashboard Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Dashboard Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}