{
 "title": "Echo Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "app" },
   { "name": "container_name", "query": "http-echo" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values({destination_service_name=~\"http-echo-service(-canary)?\"},destination_service_name)"
    }
   },
   { "name": "rollouts_namespace", "query": "argo-rollouts" }
  ]
 },
 "panels": [
  { "title": "Argo Rollouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Response Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=\"http-echo-service\"}[1m])) / (sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=\"http-echo-service\"}[1m])) + sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=\"http-echo-service-canary\"}[1m])))",
     "legendFormat": "Stable"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=\"http-echo-service-canary\"}[1m])) / (sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=\"http-echo-service\"}[1m])) + sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=\"http-echo-service-canary\"}[1m])))",
     "legendFormat": "Canary"
    }
   ]
  },
  {
   "title": "Rollouts Phase Info",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": " sum without (phase) (\n   (rollout_info{namespace=\"${rollouts_namespace}\", name=\"http-echo\", job=\"argo-rollouts-metrics\", phase=\"Completed\"} * 1) or\n   (rollout_info{namespace=\"${rollouts_namespace}\", name=\"http-echo\", job=\"argo-rollouts-metrics\", phase=\"Progressing\"} * 2) or\n   (rollout_info{namespace=\"${rollouts_namespace}\", name=\"http-echo\", job=\"argo-rollouts-metrics\", phase=\"Paused\"} * 3) or\n   (rollout_info{namespace=\"${rollouts_namespace}\", name=\"http-echo\", job=\"argo-rollouts-metrics\", phase=\"Degraded\"} * 4) or\n   (rollout_info{namespace=\"${rollouts_namespace}\", name=\"http-echo\", job=\"argo-rollouts-metrics\", phase=\"Aborted\"} * 5)\n )",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FIXME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rollouts_info_replicas_avaiable{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Istio Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=~\"$service\", response_code=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=~\"$service\", response_code=~\"3..\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=~\"$service\", response_code=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${namespace}\", destination_service_name=~\"$service\", response_code=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=\"${container_name}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${namespace}\", container=\"${container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${namespace}\", container=\"${container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${namespace}\", container=\"${container_name}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${namespace}\", container=\"${container_name}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${namespace}\", container=\"${container_name}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${namespace}\", container=\"${container_name}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${namespace}\", container=\"${container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${namespace}\", container=\"${container_name}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${namespace}\", container=\"${container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}