{
 "title": "Istio Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(destination_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (tag) (istio_build{})", "legendFormat": "{{tag}}" }
   ]
  },
  {
   "title": "istiod uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "istiod_uptime_seconds{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"3..\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Controller Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Controller Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Controller Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}