---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      serviceAccountName: ui-ksa
      # volumes:
      # - configMap:
      #     defaultMode: 420
      #     items:
      #     - key: .env
      #       path: .env.local
      #     name: ui-env-local
      #   name: ui-env-local
      containers:
        - name: ui
          image: ui:0.0.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http-ui
              containerPort: 3000
          volumeMounts:
            - mountPath: home/app/.env.local
              name: env-local
              readOnly: true
              subPath: .env.local
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: .env
                path: .env.local
            name: env-local
          name: env-local
