{
 "title": "Argo Rollouts Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "rollouts_namespace", "query": "argo-rollouts" },
   { "name": "rollouts_container_name", "query": "argo-rollouts" },
   {
    "name": "rollouts_dashboard_container_name",
    "query": "${rollouts_container_name}-dashboard"
   },
   { "name": "service", "query": "argo-rollouts-dashboard" },
   {
    "name": "rollout_name",
    "label": "Rollout Name",
    "query": {
     "query": "label_values(rollout_info{namespace=\"$rollouts_namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Rollouts Phase Info (No Completed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (phase) (rollout_info{namespace=\"${rollouts_namespace}\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Cluster Rollouts Phase Info (No Completed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (name, phase) (rollout_info{phase!=\"Completed\", namespace=\"${rollouts_namespace}\"})",
     "legendFormat": "{{name}} / {{phase}}"
    }
   ]
  },
  {
   "title": "Rollouts Replicas Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rollout_info_replicas_available{namespace=\"${rollouts_namespace}\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "rollout_info_replicas_desired{namespace=\"${rollouts_namespace}\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "rollout_info_replicas_unavailable{namespace=\"${rollouts_namespace}\"}",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Rollouts Replicas Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "rollout_info_replicas_available{namespace=\"${rollouts_namespace}\"}",
     "legendFormat": "{{name}} / Available"
    },
    {
     "expr": "rollout_info_replicas_desired{namespace=\"${rollouts_namespace}\"}",
     "legendFormat": "{{name}} / Desired"
    },
    {
     "expr": "rollout_info_replicas_unavailable{namespace=\"${rollouts_namespace}\"}",
     "legendFormat": "{{name}} / Unavailable"
    }
   ]
  },
  {
   "title": "Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (argo_rollouts_controller_info{})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Reconiliation Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "increase(rollout_reconcile_count{namespace=\"${rollouts_namespace}\"}[10m])",
     "legendFormat": "Count"
    },
    {
     "expr": "increase(rollout_reconcile_error{namespace=\"${rollouts_namespace}\"}[10m])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Controller Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"${rollouts_namespace}\", job=\"argo-rollouts-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconiliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 25 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rollout_reconcile_bucket{namespace=\"${rollouts_namespace}\"}[10m]))",
     "legendFormat": "Count"
    }
   ]
  },
  { "title": "Controller Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Controller Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Controller Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Controller Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Dashboard Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\", response_code=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\", response_code=~\"3..\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\", response_code=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\", response_code=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=\"${rollouts_namespace}\", destination_service_name=\"$service\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Dashboard Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Dashboard Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Dashboard Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${rollouts_namespace}\", container=\"${rollouts_dashboard_container_name}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}