{
 "title": "Istio Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(destination_service_name)"
    }
   },
   { "name": "istio_gateway_namespace", "query": "istio-gateway" },
   { "name": "istio_system_namespace", "query": "istio-system" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (tag) (istio_build{})", "legendFormat": "{{tag}}" }
   ]
  },
  {
   "title": "Total Destination Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (destination_service_name) (istio_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{response_code=~\"2..\"}[1m])) or vector(0)",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{response_code=~\"3..\"}[1m])) or vector(0)",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{response_code=~\"4..\"}[1m])) or vector(0)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{response_code=~\"5..\"}[1m])) or vector(0)",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(istio_requests_total{})", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "istiod uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "istiod_uptime_seconds{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Destination Service Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (destination_service_namespace) (istio_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"3..\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=~\"$service\", response_code=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"$service\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Gateway CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${istio_gateway_namespace}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${istio_gateway_namespace}\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${istio_gateway_namespace}\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Gateway Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${istio_gateway_namespace}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${istio_gateway_namespace}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${istio_gateway_namespace}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${istio_gateway_namespace}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Gateway Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${istio_gateway_namespace}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${istio_gateway_namespace}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${istio_gateway_namespace}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${istio_system_namespace}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${istio_system_namespace}\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${istio_system_namespace}\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${istio_system_namespace}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${istio_system_namespace}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${istio_system_namespace}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${istio_system_namespace}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${istio_system_namespace}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${istio_system_namespace}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${istio_system_namespace}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}