{
 "title": "Prometheus Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datsource", "query": "prometheus" },
   { "name": "prometheus_namespace", "query": "kube-prometheus-stack" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Info",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (prometheus_build_info{})",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Operator Build Info",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (prometheus_operator_build_info{})",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Operator Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_operator_ready{}", "legendFormat": "{{controller}}" }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prometheus CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"${prometheus_namespace}\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${prometheus_namespace}\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${prometheus_namespace}\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Prometheus Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"${prometheus_namespace}\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"${prometheus_namespace}\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"${prometheus_namespace}\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"${prometheus_namespace}\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Prometheus Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"${prometheus_namespace}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"${prometheus_namespace}\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"${prometheus_namespace}\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}