---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sources
  - istio
  - metrics-server
  - kube-prom-stack
  - argo-rollouts
  - headlamp

labels:
  - pairs:
      environment: playground
    # includeSelectors: true  # Updates matchLabels/selectors
    includeTemplates: true  # Updates pod template labels
