---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb
data:
  mongo-init.js: |-
    db.createUser(
      {
        user: "root",
        pwd: "mypassword",
        roles: [
            {
                role: "readWrite",
                db: "playground"
            }
        ]
      }
    );
