---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      location /nginx-health {
        return 200 "healthy\n";
        proxy_ssl_verify              off;
        # access_log  off;
      }
      location / {
        proxy_pass http://api:80;
        proxy_ssl_verify              off;
      }
    }
